name: guh
version: 0.1.0
vendor: Simon Stürz <simon.stuerz@guh.guru>
architecture: [armhf]
icon: meta/guh-logo.svg
source: https://github.com/guh/guh
license-version: "GPLv2"
services:
 - name: guhd
   start: usr/bin/guhd-wrapper.sh
   description: "guhd - Server daemon for home automation systems"
   security-template: unconfined
   caps:
    - networking
    - network-service
